---
- name: Install Windows Exporter
  hosts: 10.10.5.182
  gather_facts: yes
  tasks:
    - name: Install Prometheus Windows Exporter
      community.windows.windows_exporter:
        version: 0.18.1
      register: windows_exporter_installed
    - name: Start Windows Exporter Service
      win_service:
        name: prometheus_win_exporter
        start_mode: auto
        state: started
      when: windows_exporter_installed.changed
