---
- name: Install Prometheus Windows Exporter
  hosts: 10.10.5.182
  tasks:
    - name: Download Windows Exporter MSI
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.23.1/windows_exporter-0.23.1-amd64.msi
        dest: C:\temp\windows_exporter.msi

    - name: Install Windows Exporter
      win_msi:
        path: C:\temp\windows_exporter.msi
        arguments: '/qn'
