---
- name: Install Windows Exporter
  hosts: 10.10.5.182
  gather_facts: true
  become_method: runas
  tasks:
    - name: Create directory for Windows Exporter
      win_file:
        path: C:\Prometheus\exporter
        state: directory
    - name: Download Windows Exporter ZIP
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.23.1/windows_exporter-0.23.1-386.msi 
        dest: C:\\Prometheus\\exporter\\windows_exporter.zip
    - name: Unzip Windows Exporter
      win_unzip:
        src: C:\Prometheus\exporter\windows_exporter.zip
        dest: C:\Users\inndata-kap-002\AppData\Local\Temp\exporter
      args:
        creates: C:\Users\inndata-kap-002\AppData\Local\Temp\exporter\windows_exporter-0.23.1-amd64\windows_exporter.msi
    - name: Create Windows Exporter service
      win_command: C:\Prometheus\exporter\windows_exporter-0.23.1-amd64\windows_exporter.msi
        --install
      args:
        creates: C:\Prometheus\exporter\windows_exporter-0.23.1-amd64\windows_exporter.msi
    - name: Start Windows Exporter service
      win_service:
        name: WindowsExporter
        state: started
    - name: Enable Windows Exporter service on boot
      win_service:
        name: WindowsExporter
        enabled: yes
