---
- name: Install and Configure Windows Exporter
  hosts: 10.10.5.182  # Replace with your inventory group name

  tasks:
    - name: Download Windows Exporter
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v0.20.0/windows_exporter-0.20.0-amd64.msi"
        dest: C:\\windows_exporter.msi

    - name: Install Windows Exporter
      win_msi:
        path: C:\Temp\windows_exporter.msi
        product_id: "{{ query('win_shell', 'Get-WmiObject Win32_Product | Where-Object { $_.Name -eq ''Windows Exporter 0.20.0'' } | Select-Object -ExpandProperty IdentifyingNumber').stdout }}"
        state: present
      ignore_errors: yes

    - name: Configure Windows Exporter
      win_shell: |
        $configPath = "C:\Program Files\Windows Exporter\windows_exporter.yml"
        $config = @"
        collectors:
          enabled:
            - cpu
            - memory
            - disk
            - network
        "@
        $config | Set-Content -Path $configPath -Force
      args:
        creates: C:\Program Files\Windows Exporter\windows_exporter.yml

    - name: Start Windows Exporter Service
      win_service:
        name: windows_exporter
        start_mode: auto
        state: started
