---
- name: Install Prometheus Node Exporter on Windows
  hosts: 10.10.5.182
  gather_facts: false
  
  tasks:
    - name: Download Node Exporter ZIP
      win_get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.darwin-amd64.tar.gz
        dest: C:\temp\node_exporter.tar.gz

    - name: Extract Node Exporter
      win_shell: |
        Expand-Archive -Path C:\temp\node_exporter.tar.gz -DestinationPath C:\Program Files\NodeExporter -Force

    - name: Create Node Exporter Service
      win_shell: |
        sc.exe create NodeExporter binPath= "C:\Program Files\NodeExporter\node_exporter.exe" start= auto
      args:
        creates: HKLM\System\CurrentControlSet\Services\NodeExporter

    - name: Start Node Exporter Service
      win_service:
        name: NodeExporter
        state: started
