---
- name: Install Prometheus Windows Exporter
  hosts: 10.10.5.182
  tasks:
    - name: Download Windows Exporter MSI
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/{{ exporter_version }}/windows_exporter-{{ exporter_version }}-amd64.msi"
        dest: "C:\temp\windows_exporter.msi"

    - name: Install Windows Exporter
      win_package:
        path: "{{ destination_path }}"
        state: present
