---
- name: Install Windows Exporter
  hosts: 10.10.5.182
  tasks:
    - name: Download Windows Exporter MSI
      win_get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v0.20.0/windows_exporter-0.20.0-amd64.msi"
        dest: C:\temp\windows_exporter.msi

    - name: Install Windows Exporter
      win_msi:
        path: C:\temp\windows_exporter.msi
        arguments: '/qn'

    - name: Start Windows Exporter Service
      win_service:
        name: windows_exporter
        state: started
        start_mode: auto
