---
- name: Create Folder in Windows 10
  hosts: 10.10.5.182  # Replace with your host group name or specific host
  gather_facts: false   # We don't need to gather facts in this example

  tasks:
    - name: Create target folder
      win_file:
        path: "C:\\Users\\ansible\\Documents"  # Replace with your desired folder path
        state: directory
      register: folder_creation_result

    - name: Display result
      debug:
        var: folder_creation_result
